### ISSUE TITLE
Run --fg fails permanently on Errno::ECONNRESET

### ISSUE THREAD

**Issue by shosti** [rainforestapp/rainforest-cli#100]
See https://circleci.com/gh/rainforestapp/Rainforest/19902: there was an SSL "Connection reset by peer" error, which caused the build to fail, but the RF test actually ended up passing.
## Expected behavior

Resiliency to temporary connectivity errors to the API.
## Actual behavior

Instant exit with exit code 1.

**Comment by jkaipr** [comment]
@shosti is this still an issue? Mariana closed the duplicate issue with a comment that it's not happening anymore.

**Comment by epaulet** [comment]
We haven't made any changes in the CLI for being resilient to this.

**Comment by ukd1** [comment]
Closing as it's for the ruby version
