### ISSUE TITLE
Failing validation

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/rainforest-cli#110]
Our circle builds fail often because of this problem and I'm not sure what this is or why it is happening, mind taking a look @epaulet @ukd1 

![image](https://cloud.githubusercontent.com/assets/1188186/15475030/0cc9c67a-2108-11e6-9af7-2f306143e57c.png)

**Comment by epaulet** [comment]
It's happening because the server is returning an error. We validate to make sure you aren't using a RFML id from any tests, whether they are local or remote. In other words, this is a bug with the main app. But, I think we could find a way to make the client more tolerant of this kind of error.

**Comment by juliankrispel** [comment]
Oh I see, annoying

**Comment by epaulet** [comment]
This should have been taken care of in #199
