### ISSUE TITLE
upload doesn't upload steps if there is an error

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/rainforest-cli#130]
Steps to reproduce:

1 - Create a test with an invalid start_uri (which passes validation)
2 - Try to upload a bunch of tests
3 - The tests will be created with all browsers and 0 steps.

**Comment by epaulet** [comment]
This is intentional because you may want to embed a test that has never been uploaded before, in which case the API will not allow you. To work around this, we create blank tests for anything that hasn't been uploaded before, then update all the tests.

**Comment by fuzzylita** [comment]
Is this not really an issue then, @epaulet?

**Comment by epaulet** [comment]
I mean we can change the behavior, but I think in the future we are going to need to find a way to just send the tests to the server in bulk and avoid the multi-step upload process
