### ISSUE TITLE
Add option to runs tests in the repo

### ISSUE THREAD

**Issue by usami** [rainforestapp/rainforest-cli#150]
@shosti suggested

> Move **all** tests to RFML and fix the CLI so that it optionally only runs the tests in the repo

maybe add way to specify tests to run by file/folder?

**Comment by epaulet** [comment]
I'm thinking this could be possible by uploading the tests, saving the ids, and then using those ids to filter the ids for the run.

**Comment by shosti** [comment]
Easier (hacky) solution: upload tests with a UUID tag for the run, start the run with that tag, then untag all those tests. Wouldn't need many changes to our existing API. Only problem: it's vulnerable to race conditions/bad failure modes.

**Comment by epaulet** [comment]
Until we fix upload to not fail every so often, we are going to have lots of phantom tags using that method I think

**Comment by epaulet** [comment]
This has been implemented with #287
