### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by ithinkdancan** [rainforestapp/rainforest-cli#181]
with the latest CLI release when running `rainforest upload`  we are now seeing this error. 

F, [2016-08-19T18:36:10.929335 #71360] FATAL -- : Error: 9e521638-f15f-4175-bb82-b6296f54cea3: (Status 404) {"error":"Account not found"}  

Any idea what changed to break the upload?

**Comment by epaulet** [comment]
@ithinkdancan There was an authentication up in 1.8.0. This should be fixed in 1.8.1.
