### ISSUE TITLE
Account Not Found on CSV Upload

### ISSUE THREAD

**Issue by slin1202** [rainforestapp/rainforest-cli#203]
Hi just started using the cli and I'm getting this error. 

```
F, [2016-10-26T14:44:02.209498 #3019] FATAL -- : Non 200 code received for request to https://app.rainforestqa.com/api/1/generators
F, [2016-10-26T14:44:02.209578 #3019] FATAL -- : Server response: {"error":"Account not found"}
```

Any idea what it means, I'm pretty sure the API key is correct?

**Comment by epaulet** [comment]
Hi @slin1202 - this usually means that the API key is incorrect or missing. Are you supplying your token with the `--token` option?

**Comment by slin1202** [comment]
Thanks for getting back so soon. I have it set as an environment variable but to be honest I may have misinterpreted what the csv-upload command does. Is it the same as me going into the site and uploading a csv in the Tabular Variables table? Will try it with the token option though as it's possible my variable wasn't set correctly.

**Comment by epaulet** [comment]
It's the same functionality as that. If this keeps happening after you've double-checked everything, it would be helpful to paste your command (with your API token redacted) and options here to see if I can reproduce.

**Comment by slin1202** [comment]
Tried it with token and it worked, so I must have set the env var incorrectly. Sorry about that, thanks!
