### ISSUE TITLE
commands not documented in cli help

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/rainforest-cli#222]
just the options:

![image](https://cloud.githubusercontent.com/assets/1188186/20883780/c66a2590-badf-11e6-8d1d-f9da2d13cf7b.png)

I would expect the cli help to show the commands as well

**Comment by Taytay** [comment]
I am currently running up against this. I ran `rainforest sites` and got `F, [2016-12-08T22:51:57.321063 #5210] FATAL -- : Unknown command`. So I then ran just `rainforest` and I see only the options. I don't know which commands are valid.

**Comment by Taytay** [comment]
After I installed the most recent version of the gem, it appears to work. Now I'm on 1.11.0:
```
$ rainforest --version
Rainforest CLI 1.11.0
```

**Comment by juliankrispel** [comment]
@Taytay awesome - we were just about to suggest that :+1:
