### ISSUE TITLE
random console output when uploading tests

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/rainforest-cli#225]
Not sure what the point is in outputting this. It's either very bad copy or just a mistake

![image](https://cloud.githubusercontent.com/assets/1188186/20884836/78cb188e-bae5-11e6-9498-0fd59e718a6a.png)

**Comment by epaulet** [comment]
I can't duplicate this in the latest version.

**Comment by epaulet** [comment]
This seems like an issue with an older version. I haven't been able to reproduce or find in the code. Closing for now.
