### ISSUE TITLE
[GO Cli] - upload command not working as expected

### ISSUE THREAD

**Issue by juliankrispel** [rainforestapp/rainforest-cli#245]
It looks like there are new tests created for old rfml ids...

[The failure can be seen here in circle](https://circleci.com/gh/rainforestapp/regenwald/7700?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by macocha** [comment]
fixed in https://github.com/rainforestapp/rainforest-cli/pull/243
