### ISSUE TITLE
Give meaningful feedback when there are no column headers

### ISSUE THREAD

**Issue by jipiboily** [rainforestapp/rainforest-cli#25]
Right now, it just crashes.

**Comment by shosti** [comment]
@jipiboily Can you give some more details? We already do some rudimentary checking:

```
        # Create the generator
        columns = rows.shift.map do |column|
          {name: column.downcase.strip.gsub(/\s/, '_')}
        end
        raise 'Invalid schema in CSV. You must include headers in first row.' if not columns
```

**Comment by jipiboily** [comment]
I don't have much more details to be honest, sorry. It looks to me that this code should be enough for now. Let's close it for now and re-open if we face that again, with more details.
