### ISSUE TITLE
Command failure does not return error code

### ISSUE THREAD

**Issue by tptodorov** [rainforestapp/rainforest-cli#312]
`
  rainforest run --token $RAINFOREST_TOKEN --fg --fail-fast --description "CircleCI 
  $CIRCLE_BUILD_NUM $CIRCLE_BUILD_URL" --tag other

 Incorrect Usage.
`
echo $?
0

Should be an error.

**Comment by epaulet** [comment]
Original solution was reverted due to errors with upgrading a dependency. Re-opening.

**Comment by epaulet** [comment]
Fixed by #319
