### ISSUE TITLE
Support running under Alpine linux

### ISSUE THREAD

**Issue by shadowfax-chc** [rainforestapp/rainforest-cli#345]
Alpine is a common distro for docker images. However it uses [musl libc](https://www.musl-libc.org/) instead of glibc. As such, the current linux binary does not run under alpine. It errors out with the rather cryptic `rainforest: not found` since, although the binary is there, the library it is linked against is not.

One way to resolve this would be to compile a static binary instead of a dynamic one. This can be done with:

```
GCO_ENABLED=0 go build -x -ldflags "-extldflags -static"
```

**Comment by roman-dowakin** [comment]
Hello, sorry for long response.

Right now, in dev channel `https://dl.equinox.io/rainforest_qa/rainforest-cli/dev` rainforest-cli is statically build. We will release new version soon.

Also, as current workaround, you can install one additional package in Alpine `apk add --no-cache libc6-compat`

The PR with fix: https://github.com/rainforestapp/rainforest-cli/pull/393
