### ISSUE TITLE
Add retry limit parameter to cli to retry failed tests automatically for easier integration

### ISSUE THREAD

**Issue by BlankMatter** [rainforestapp/rainforest-cli#396]
### Problem
We are using Rainforest qa extensively and currently run into flaky tests which are based on the Rainforest qa virtual machine performance. In addition tests can also be flaky by nature if the application they are testing is not well designed. Using a service like gitlab with the Rainforest cli leads to the problem that when hitting the "retry" button on a failed job triggers all rainforest tests again, if failed or not. This leads to following issues:

- All rainforest tests of that run-group are triggered again, which makes it more expensive and the pipeline takes longer than if only the failed tests would be re-triggered
- Flaky tests that succeeded in the previous run may now fail since if every flaky test has a certain percentage to fail, re-running all tests does not decrease the overall chance for the pipeline to succeed
- Rainforest tests manually re-triggered in the app.rainforestqa console won't be reported back to the failed stage since connection is already terminated and the process exited with a failure code

### Proposed Solution
Adding an additional parameter to the cli run command that allows to define how often failed tests can be retried would allow to only re-run failed tests without the need of adding a custom script or using a workaround like chaining the retry command independent of if the first run succeeded or not. This is a common concept used in many ci services allowing the developer to set a maximum retry limit. The default limit if not parameter is given could be set to 1 which would not have any impact on current setups of the cli.

The parameter could be used like this
`docker run gcr.io/rf-public-images/rainforest-cli run --run-group 1234 --max-retry 3`

### Benefit
With only a single parameter the problem would be universally solved for any shell or environment. It also makes the rerun command independent of the RAINFOREST_RUN_ID variable in the environment

**Comment by maciejgryka** [comment]
Thanks for the suggestion @BlankMatter, we're looking into it.

**Comment by maciejgryka** [comment]
@BlankMatter after playing with it for a while, my favorite solution so far would be adding a flag to the `run` command, which would either start a new run OR re-run the last run with the same settings if the last one failed.

Specifically, you'd do something like `rainforest-cli run --run-group 123 --rerun-if-last-failed` and could run it in a loop until it succeeds. If it fails and you run it again, it'd find the last run with the same Run Group, realize it failed and re-run just the failed tests from that. If it fails again and you run the same command again, it'd look at the most recent re-run and re-run the failed test from that etc.

This still requires some adjustments to your CI, but they feel pretty easy (e.g. you could use [GitLab's retry](https://docs.gitlab.com/ee/ci/yaml/#retry)).

Do you think that'd give you the behavior you're after?

**Comment by maciejgryka** [comment]
@BlankMatter I've pushed a beta version of the CLI, now with support for `--max-reruns` https://dl.equinox.io/rainforest_qa/rainforest-cli/beta). We'll probably release it to the stable channel some time next week, FYI.

**Comment by ChristianBlank** [comment]
This is great, thank you!

**Comment by maciejgryka** [comment]
This has now been [released as version 2.18.0](https://github.com/rainforestapp/rainforest-cli/pull/399) and the CLI should update automatically once you run it.
