### ISSUE TITLE
--custom-url adds a trailing slash to URL

### ISSUE THREAD

**Issue by alanb43** [rainforestapp/rainforest-cli#473]
When using the "--custom-url" option in a github action (and possibly all of the time), the url that is passed to the test runner has a trailing slash. In my use case, the url I'm passing is a download link, and the slash is causing the download to not work / the response to be an XML error. Let me know if this is on my end!

**Comment by magni-** [comment]
Hi @alanb43

The temporary environment's URL is properly created without a trailing slash, so there's no issue on the CLI (of GitHub Action)'s side of things. What's happening is that the test's `start_uri` is currently set to `/`, so the test starts off navigating to `{environment_url}/`.

If you set your tests' `start_uri` to the empty string, your tests will start off navigating to `{environment_url}`. This must currently be done via the API, see [the `put-test` endpoint](https://help.rainforestqa.com/reference/put-test).

Alternatively, you can add a Navigate step, navigating to `{{ rainforest.url_base }}`. This will navigate to `{environment_url}`, regardless of what the test's `start_uri` is.

**Comment by magni-** [comment]
A hackier solution would be to append `#` or `?` to the `--custom-url`. This means the file will be properly downloaded even with an extra `/` at the end of the URL.
