### ISSUE TITLE
Add ability to run tests with smart folder name

### ISSUE THREAD

**Issue by LFDanLu** [rainforestapp/rainforest-cli#60]
It would be nice to be able to specify a smart folder name to run a group of tests.

**Comment by epaulet** [comment]
We just added the reference your site IDs in this format:
```
$ bin/rainforest sites
Site ID | Site Name
-------------------
   5425 | Baz Site
   5312 | Foo Site
   5424 | Bar Site
```

For consistency, it might be sense to do this for smart folders as well. It also means you wouldn't have to worry about mispelling your folder name. Would that cover the use case?

**Comment by LFDanLu** [comment]
Ahhh, yes that would work. Thanks!
